version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1
  api:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          memory: 50M
volumes:
  mongodata:

networks:
  network1: